[package]
name = "task-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["clock", "serde"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
